name: Build Linux

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Build
        run: go build -tags prod -o svema_uploader_linux .

      - uses: actions/upload-artifact@v4
        with:
          name: svema_uploader_linux
          path: svema_uploader_linux
