name: Build macOS

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  build-macos-arm:
    runs-on: macos-latest   # Apple Silicon (arm64)
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: brew install pkgconf

      - name: Build
        run: go build -tags prod -o svema_uploader_macos_arm64 .

      - uses: actions/upload-artifact@v4
        with:
          name: svema_uploader_macos_arm64
          path: svema_uploader_macos_arm64
